# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bloodline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('generation', models.IntegerField(default=12)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('clan_rank', models.IntegerField()),
                ('willpower', models.IntegerField()),
                ('humanity', models.IntegerField()),
                ('frenzy', models.IntegerField()),
                ('bloodpool', models.IntegerField()),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.AgeCategory')),
                ('bloodline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Bloodline')),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalFuntion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='gm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm', to='domainmanager.Person'),
        ),
        migrations.AddField(
            model_name='domain',
            name='substitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='domainmanager.Person'),
        ),
        migrations.AddField(
            model_name='character',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Clan'),
        ),
        migrations.AddField(
            model_name='character',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.PoliticalFuntion'),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Gender'),
        ),
        migrations.AddField(
            model_name='character',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Rank'),
        ),
        migrations.AddField(
            model_name='character',
            name='salutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Salutation'),
        ),
        migrations.AddField(
            model_name='bloodline',
            name='parent_clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Clan'),
        ),
    ]
