# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0002_auto_20160503_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vampire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='domainmanager.Vampire')),
            ],
        ),
    ]
