# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0005_auto_20160503_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='vampire',
            name='generation',
            field=models.IntegerField(default=10),
        ),
    ]
