# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0006_vampire_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vampire',
            name='column',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vampire',
            name='generation',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
