# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0008_auto_20160504_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='boon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='domainmanager.Category'),
        ),
        migrations.AddField(
            model_name='boon',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='domainmanager.Person'),
        ),
        migrations.AddField(
            model_name='boon',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave', to='domainmanager.Person'),
        ),
    ]
