# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0009_auto_20160509_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BoonCategory',
        ),
    ]
