# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0013_auto_20160513_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salutation',
            old_name='salutation',
            new_name='name',
        ),
    ]
