# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0019_auto_20160515_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_sire', to='domainmanager.Character'),
        ),
    ]
