# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0031_vampire_clan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodline',
            name='parent_clan',
        ),
        migrations.RemoveField(
            model_name='character',
            name='bloodline',
        ),
        migrations.AddField(
            model_name='clan',
            name='bloodline',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='clan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentclan', to='domainmanager.Clan'),
        ),
        migrations.DeleteModel(
            name='Bloodline',
        ),
    ]
