# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0032_auto_20160720_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='bloodline',
        ),
    ]
