# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0034_auto_20160720_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_domain', to='domainmanager.Domain'),
        ),
    ]
