# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0035_person_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='xp',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='domainmanager.Character'),
        ),
        migrations.AddField(
            model_name='xp',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='xp',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='domainmanager.Event'),
        ),
    ]
