# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0036_auto_20160720_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.AgeCategory'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bloodpool',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='clan_rank',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_of_death',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='frenzy',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Gender'),
        ),
        migrations.AlterField(
            model_name='character',
            name='humanity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Rank'),
        ),
        migrations.AlterField(
            model_name='character',
            name='salutation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Salutation'),
        ),
        migrations.AlterField(
            model_name='character',
            name='willpower',
            field=models.IntegerField(default=5),
        ),
    ]
