# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0037_auto_20160721_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='clan_rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_of_death',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='character',
            name='salutation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Salutation'),
        ),
    ]
