# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0039_auto_20160723_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='boon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 24, 9, 47, 31, 881696, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boon',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 24, 9, 47, 38, 928823, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 24, 9, 47, 41, 53727, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 24, 9, 47, 43, 38197, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterproperty',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 24, 9, 47, 44, 788249, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterproperty',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 24, 9, 47, 46, 507069, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 24, 9, 47, 51, 207107, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xp',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 24, 9, 47, 53, 347934, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character_domain', to='domainmanager.Domain'),
        ),
    ]
