# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0043_auto_20160724_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdiscipline',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cd_character', to='domainmanager.Character'),
        ),
        migrations.AlterField(
            model_name='characterproperty',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_character', to='domainmanager.Character'),
        ),
    ]
