# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0044_auto_20160724_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='nickname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='lastname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
