# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 10:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0045_auto_20160724_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='initial',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
