# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 14:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0047_auto_20160724_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='initial',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
