# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0048_auto_20160724_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterdiscipline',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterdiscipline',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='clan',
        ),
        migrations.DeleteModel(
            name='CharacterDiscipline',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
