# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0049_auto_20160726_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Clan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Property')),
            ],
        ),
        migrations.AddField(
            model_name='clan',
            name='disciplines',
            field=models.ManyToManyField(through='domainmanager.ClanProperty', to='domainmanager.Property'),
        ),
    ]
