# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0050_auto_20160726_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xpearned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Character')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='domainmanager.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Xpspent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Character')),
                ('property', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Property')),
            ],
        ),
        migrations.RemoveField(
            model_name='xp',
            name='character',
        ),
        migrations.RemoveField(
            model_name='xp',
            name='event',
        ),
        migrations.DeleteModel(
            name='Xp',
        ),
    ]
