# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 18:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0051_auto_20160727_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterproperty',
            name='value',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
