# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0052_auto_20160727_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='xpmultiplier',
            field=models.IntegerField(default=1),
        ),
    ]
