# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0054_auto_20160727_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpspent',
            name='xpcost',
            field=models.IntegerField(default=1),
        ),
    ]
