# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0055_xpspent_xpcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boon',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='domainmanager.Character'),
        ),
        migrations.AlterField(
            model_name='boon',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave', to='domainmanager.Character'),
        ),
    ]
