# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0056_auto_20160728_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boon',
            name='date',
        ),
        migrations.AddField(
            model_name='boon',
            name='note',
            field=models.TextField(default='please fill out a short decription'),
        ),
    ]
