# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0057_auto_20160728_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boon',
            name='description',
        ),
    ]
