# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0059_boonworkflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boonworkflow',
            name='boon',
        ),
        migrations.RenameField(
            model_name='boon',
            old_name='note',
            new_name='masternote',
        ),
        migrations.AddField(
            model_name='boon',
            name='approvedbygm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boon',
            name='approvedbygm_note',
            field=models.TextField(default='Place for additional notes'),
        ),
        migrations.AddField(
            model_name='boon',
            name='approvedbyslave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boon',
            name='approvedbyslave_note',
            field=models.TextField(default='Place for additional notes'),
        ),
        migrations.DeleteModel(
            name='Boonworkflow',
        ),
    ]
