# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0060_auto_20160728_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='boon',
            name='hash',
            field=models.CharField(default='', max_length=20),
        ),
    ]
