# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0061_boon_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boon',
            old_name='hash',
            new_name='hash_gm',
        ),
        migrations.AddField(
            model_name='boon',
            name='hash_slave',
            field=models.CharField(default='', max_length=20),
        ),
    ]
