# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 18:06
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0062_auto_20160728_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boon',
            name='approvedbygm',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='waiting', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='boon',
            name='approvedbyslave',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='waiting', max_length=100, no_check_for_status=True),
        ),
    ]
