# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0063_auto_20160728_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boon',
            old_name='masternote',
            new_name='note',
        ),
    ]
