# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0064_auto_20160728_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boon',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='domainmanager.Character'),
        ),
    ]
