# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0067_auto_20160729_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='boon',
            name='hast_gm',
            field=models.CharField(default='', max_length=20),
        ),
    ]
