# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0069_remove_boon_hast_gm'),
    ]

    operations = [
        migrations.AddField(
            model_name='boon',
            name='hash_master',
            field=models.CharField(default='', max_length=20),
        ),
    ]
