# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0071_auto_20160729_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='initatcharactercreation',
            new_name='initalizecharactercreation',
        ),
        migrations.RemoveField(
            model_name='property',
            name='initial',
        ),
        migrations.AddField(
            model_name='propertytype',
            name='xpinitialprize',
            field=models.IntegerField(default=5),
        ),
    ]
