# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 09:43
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0073_auto_20160729_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='standardclan',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=1, max_length=100, no_check_for_status=True),
        ),
    ]
