# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0075_character_secretclan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
