# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0076_auto_20160731_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='stattype',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=4, max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
