# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0077_auto_20160731_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterproperty',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Character'),
        ),
        migrations.AlterField(
            model_name='characterproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Property'),
        ),
    ]
