# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 17:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0078_auto_20160802_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250)),
                ('preface', models.TextField(default='Add an introduction here')),
                ('content', models.TextField(verbose_name='Add the main content here')),
                ('link', models.CharField(max_length=250)),
                ('validfrom', models.DateField(blank=True, null=True)),
                ('validuntil', models.DateField(blank=True, null=True)),
                ('shreknetlevel', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('isvision', model_utils.fields.StatusField(choices=[(1, 'Yes'), (2, 'No')], default=2, max_length=100, no_check_for_status=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('limittoclan', models.ManyToManyField(to='domainmanager.Clan')),
            ],
        ),
    ]
