# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 17:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0079_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='shreknetlevel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
