# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 17:09
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0080_auto_20160803_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='isvision',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='no', max_length=100, no_check_for_status=True),
        ),
    ]
