# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0081_auto_20160803_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='isvision',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=1, max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
