# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0082_auto_20160803_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='isvision',
            field=models.BooleanField(default=False),
        ),
    ]
