# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0085_auto_20160803_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
