# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0088_event_domains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='domain',
            new_name='domains',
        ),
    ]
