# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0089_auto_20160804_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='domains',
        ),
        migrations.AddField(
            model_name='event',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
            preserve_default=False,
        ),
    ]
