# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 12:52
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0092_auto_20160813_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='stattype',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=4, max_length=100, no_check_for_status=True),
        ),
    ]
