# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0093_auto_20160813_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='firstname',
            field=models.CharField(default='David', max_length=200),
            preserve_default=False,
        ),
    ]
