# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 18:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0094_auto_20160813_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='generation',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(4)]),
        ),
    ]
