# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0095_auto_20160813_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='startingxp',
            field=models.IntegerField(default=25),
        ),
    ]
