# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0096_agecategory_startingxp'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpearned',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
