# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import domainmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0097_xpearned_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='limittoclan',
            field=models.ManyToManyField(blank=True, null=True, to='domainmanager.Clan'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='rank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='sect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
    ]
