# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import domainmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0098_auto_20160814_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
        migrations.AddField(
            model_name='clan',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
        migrations.AddField(
            model_name='rank',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
        migrations.AddField(
            model_name='sect',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
    ]
