# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0099_auto_20160814_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='standardclan',
            field=models.IntegerField(choices=[(1, 'Standard clan'), (2, 'Restricted clan')], default=1),
        ),
    ]
