# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0100_auto_20160814_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boon',
            name='approvedbygm',
            field=models.IntegerField(choices=[(1, 'Waiting for approval'), (2, 'Accepted'), (3, 'Declined'), (4, 'Resolved')], default=1),
        ),
        migrations.AlterField(
            model_name='boon',
            name='approvedbymaster',
            field=models.IntegerField(choices=[(1, 'Waiting for approval'), (2, 'Accepted'), (3, 'Declined'), (4, 'Resolved')], default=1),
        ),
        migrations.AlterField(
            model_name='boon',
            name='approvedbyslave',
            field=models.IntegerField(choices=[(1, 'Waiting for approval'), (2, 'Accepted'), (3, 'Declined'), (4, 'Resolved')], default=1),
        ),
        migrations.AlterField(
            model_name='charactershopping',
            name='approvedbygm',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Accepted'), (3, 'Declined'), (4, 'Resolved'), (5, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='limittoclan',
            field=models.ManyToManyField(blank=True, to='domainmanager.Clan'),
        ),
        migrations.AlterField(
            model_name='property',
            name='initalizeatcharactercreation',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='stattype',
            field=models.IntegerField(choices=[(1, 'Physical'), (2, 'Social'), (3, 'Mental'), (4, 'Talents'), (5, 'Skills'), (6, 'Knowledges'), (7, 'Backgrounds'), (8, 'Disciplines'), (9, 'Merits'), (10, 'Flaws'), (11, 'Rituals'), (12, 'Thaumaturgic Paths'), (13, 'Necromantic Paths')], default=4),
        ),
    ]
