# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0101_auto_20160814_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
