# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 18:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0102_person_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shreknetlevel',
        ),
        migrations.AddField(
            model_name='news',
            name='schreknetlevel',
            field=models.IntegerField(default=0, help_text='Does it require SchrekNet access?', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='news',
            name='isvision',
            field=models.BooleanField(default=False, help_text='Is it a vision?'),
        ),
    ]
