# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0103_auto_20160814_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agecategory',
            options={'verbose_name_plural': 'Age categories'},
        ),
        migrations.AlterModelOptions(
            name='booncategory',
            options={'verbose_name_plural': 'Boon categories'},
        ),
        migrations.AlterModelOptions(
            name='characterproperty',
            options={'verbose_name_plural': 'Character properties'},
        ),
        migrations.AlterModelOptions(
            name='clanproperty',
            options={'verbose_name_plural': 'clan properties'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='xpearned',
            options={'verbose_name_plural': 'XPs earned'},
        ),
        migrations.AlterModelOptions(
            name='xpspent',
            options={'verbose_name_plural': 'XPs spent'},
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Person'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='Add the main content here'),
        ),
    ]
