# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 10:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0104_auto_20160814_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hasvisions',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Active'), (4, 'Passive')], default=2),
        ),
        migrations.AddField(
            model_name='character',
            name='schrecknetlevel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='active',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Active'), (4, 'Passive')], default=3),
        ),
    ]
