# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0109_auto_20160821_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertytype',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
