# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0110_auto_20160821_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name_plural': 'Characters'},
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Insert event title', max_length=100),
        ),
        migrations.AlterField(
            model_name='xpearned',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Event'),
        ),
    ]
