# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0114_auto_20160823_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clan',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
