# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0118_auto_20160824_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='gender',
        ),
        migrations.AddField(
            model_name='gender',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
        migrations.AddField(
            model_name='gender',
            name='name',
            field=models.CharField(default='Something', max_length=25),
            preserve_default=False,
        ),
    ]
