# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0119_auto_20160824_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_domain', to='domainmanager.Domain'),
        ),
        migrations.AddField(
            model_name='salutation',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_country', to='domainmanager.Country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Salutation'),
        ),
    ]
