# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0120_auto_20160824_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='booncategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booncategory',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booncategory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
