# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0121_auto_20160824_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpearned',
            name='character',
        ),
        migrations.AddField(
            model_name='xpearned',
            name='character',
            field=models.ManyToManyField(null=True, to='domainmanager.Character'),
        ),
    ]
