# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0122_auto_20160825_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpearned',
            name='character',
        ),
        migrations.AddField(
            model_name='xpearned',
            name='characters',
            field=models.ManyToManyField(to='domainmanager.Character'),
        ),
    ]
