# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0123_auto_20160825_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='active',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Passive')], default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='hasvisions',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2, help_text='Has the character visions?', verbose_name='Visions'),
        ),
    ]
