# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0124_auto_20160825_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactershopping',
            name='newproperty',
        ),
        migrations.RemoveField(
            model_name='charactershopping',
            name='newpropertytype',
        ),
    ]
