# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0126_auto_20160831_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
