# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0128_action_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Character'),
            preserve_default=False,
        ),
    ]
