# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0130_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='start',
            field=models.DateField(),
        ),
    ]
