# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import domainmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0131_auto_20161004_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='attachment',
            new_name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path),
        ),
        migrations.AddField(
            model_name='downtime',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
