# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0134_agecategory_startingsecrets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Character')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Secret')),
            ],
            options={
                'verbose_name_plural': 'Character secrets',
            },
        ),
    ]
