# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0136_auto_20161005_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
            preserve_default=False,
        ),
    ]
