# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0138_auto_20161007_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='genealogy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genealogy',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
