# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0140_action_downtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
    ]
