# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0141_remove_action_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Insert event title', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
    ]
