# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0142_auto_20161007_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='genealogy',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
    ]
