# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0143_genealogy_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genealogy',
            options={'verbose_name_plural': 'Genealogy'},
        ),
    ]
