# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0144_auto_20161008_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genealogy',
            name='generation',
        ),
        migrations.AddField(
            model_name='genealogy',
            name='current_generation',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='genealogy',
            name='initial_generation',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
