# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0147_domain_boons'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactershopping',
            name='mentor',
            field=models.BooleanField(default=False, help_text='Do you posses a corresponding mentor?'),
        ),
    ]
