# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0148_charactershopping_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='mentor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='mentorbonus',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='charactershopping',
            name='mentor',
            field=models.BooleanField(default=False, help_text='Do you have access to a mentor?'),
        ),
    ]
