# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0149_auto_20161014_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, default='please insert a useful manual text', null=True),
        ),
    ]
