# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0150_auto_20161014_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='genealogy',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='sire',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
