# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0151_auto_20161016_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='startingabilites',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='startingdisciplines',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='agecategory',
            name='startingskills',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='character',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
