# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0152_auto_20161016_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='startingbackgrounds',
            field=models.IntegerField(default=5),
        ),
    ]
