# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0154_domain_advancedcharactercreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='startinginfluences',
            field=models.IntegerField(default=4),
        ),
    ]
