# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0155_agecategory_startinginfluences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.IntegerField(default=0)),
                ('skills', models.IntegerField(default=0)),
                ('disciplines', models.IntegerField(default=0)),
                ('backgrounds', models.IntegerField(default=0)),
                ('influences', models.IntegerField(default=0)),
                ('secrets', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Character')),
            ],
            options={
                'verbose_name_plural': 'Character creation entries',
            },
        ),
    ]
