# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0156_charactercreation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agecategory',
            old_name='startingabilites',
            new_name='startingabilities',
        ),
    ]
