# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0158_auto_20161115_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercreation',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Character'),
        ),
    ]
