# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0159_auto_20161115_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='levelup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='stattype',
            field=models.IntegerField(choices=[(1, 'Physical'), (2, 'Social'), (3, 'Mental'), (4, 'Talents'), (5, 'Skills'), (6, 'Knowledges'), (7, 'Backgrounds'), (8, 'Disciplines'), (9, 'Merits'), (10, 'Flaws'), (11, 'Rituals'), (12, 'Thaumaturgic Paths'), (13, 'Necromantic Paths'), (14, 'Influences'), (15, 'Secrets')], default=4),
        ),
    ]
