# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0160_auto_20161116_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quickedit',
            field=models.BooleanField(default=False),
        ),
    ]
