# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0161_character_quickedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='limit',
            field=models.IntegerField(default=5),
        ),
    ]
