# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0162_agecategory_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agecategory',
            old_name='limit',
            new_name='lvluplimit',
        ),
    ]
