# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0163_auto_20161121_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='advancedlvluplimit',
            field=models.IntegerField(default=3),
        ),
    ]
