# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 18:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import domainmanager.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0164_agecategory_advancedlvluplimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchreckNetMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250)),
                ('preface', tinymce.models.HTMLField(default='Add an introduction here')),
                ('content', tinymce.models.HTMLField(default='Add the main content here')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('schrecknetlevel', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'SchreckNet messages',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=250)),
                ('preface', tinymce.models.HTMLField(default='Add an introduction here')),
                ('content', tinymce.models.HTMLField(default='Add the main content here')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=domainmanager.models.set_upload_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('visionlevel', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Visions',
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='hasvisions',
        ),
        migrations.RemoveField(
            model_name='news',
            name='isvision',
        ),
        migrations.RemoveField(
            model_name='news',
            name='limittoclan',
        ),
        migrations.RemoveField(
            model_name='news',
            name='schreknetlevel',
        ),
        migrations.AddField(
            model_name='character',
            name='visionlevel',
            field=models.IntegerField(default=0, help_text='What is the vision level of the character?', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Vision level'),
        ),
        migrations.AlterField(
            model_name='character',
            name='schrecknetlevel',
            field=models.IntegerField(default=0, help_text='What is the Schrecknet level of the character?', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Schrecknet level'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(default='Add the main content here'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preface',
            field=tinymce.models.HTMLField(default='Add an introduction here'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Person'),
        ),
        migrations.AddField(
            model_name='vision',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
        migrations.AddField(
            model_name='schrecknetmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Person'),
        ),
        migrations.AddField(
            model_name='schrecknetmessage',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
    ]
