# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0165_auto_20161123_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchreckNetMessage',
            new_name='SchreckNet',
        ),
    ]
