# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0166_auto_20161123_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='schrecknet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='visions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schrecknet',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indomain', to='domainmanager.Domain'),
        ),
    ]
