# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0167_auto_20161123_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='schrecknet',
            new_name='schrecknetmessages',
        ),
        migrations.AlterField(
            model_name='schrecknet',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
        ),
    ]
