# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanager', '0168_auto_20161123_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanproperty',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domainmanager.Domain'),
            preserve_default=False,
        ),
    ]
